
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.18.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Default {
    using System;
    using Terminal.Gui;
    
    
    public partial class MyDialog : Terminal.Gui.Window {
        
        private Terminal.Gui.Label label1;
        
        private Terminal.Gui.DateField datefield1;
        
        private Terminal.Gui.Label label2;
        
        private Terminal.Gui.TextField textfield1;
        
        private Terminal.Gui.Label label12;
        
        private Terminal.Gui.Label label14;
        
        private Terminal.Gui.Label label13;
        
        private Terminal.Gui.Label label3;
        
        private Terminal.Gui.TextField textfield2;
        
        private Terminal.Gui.Label label15;
        
        private Terminal.Gui.Label label4;
        
        private Terminal.Gui.TextField textfield3;
        
        private Terminal.Gui.Label label16;
        
        private Terminal.Gui.Label label5;
        
        private Terminal.Gui.Label label17;
        
        private Terminal.Gui.Label label6;
        
        private Terminal.Gui.Label label18;
        
        private Terminal.Gui.Label label7;
        
        private Terminal.Gui.Label label19;
        
        private Terminal.Gui.Label label8;
        
        private Terminal.Gui.Label label20;
        
        private Terminal.Gui.Label label9;
        
        private Terminal.Gui.Label label21;
        
        private Terminal.Gui.Label label10;
        
        private Terminal.Gui.Label label22;
        
        private Terminal.Gui.Label label11;
        
        private Terminal.Gui.Label label23;
        
        private Terminal.Gui.Label label232;
        
        private Terminal.Gui.Label label112;
        
        private Terminal.Gui.Label label1123;
        
        private Terminal.Gui.Label label11232;
        
        private Terminal.Gui.Label label1122;
        
        private Terminal.Gui.Label label112322;
        
        private void InitializeComponent() {
            this.label112322 = new Terminal.Gui.Label();
            this.label1122 = new Terminal.Gui.Label();
            this.label11232 = new Terminal.Gui.Label();
            this.label1123 = new Terminal.Gui.Label();
            this.label112 = new Terminal.Gui.Label();
            this.label232 = new Terminal.Gui.Label();
            this.label23 = new Terminal.Gui.Label();
            this.label11 = new Terminal.Gui.Label();
            this.label22 = new Terminal.Gui.Label();
            this.label10 = new Terminal.Gui.Label();
            this.label21 = new Terminal.Gui.Label();
            this.label9 = new Terminal.Gui.Label();
            this.label20 = new Terminal.Gui.Label();
            this.label8 = new Terminal.Gui.Label();
            this.label19 = new Terminal.Gui.Label();
            this.label7 = new Terminal.Gui.Label();
            this.label18 = new Terminal.Gui.Label();
            this.label6 = new Terminal.Gui.Label();
            this.label17 = new Terminal.Gui.Label();
            this.label5 = new Terminal.Gui.Label();
            this.label16 = new Terminal.Gui.Label();
            this.textfield3 = new Terminal.Gui.TextField();
            this.label4 = new Terminal.Gui.Label();
            this.label15 = new Terminal.Gui.Label();
            this.textfield2 = new Terminal.Gui.TextField();
            this.label3 = new Terminal.Gui.Label();
            this.label13 = new Terminal.Gui.Label();
            this.label14 = new Terminal.Gui.Label();
            this.label12 = new Terminal.Gui.Label();
            this.textfield1 = new Terminal.Gui.TextField();
            this.label2 = new Terminal.Gui.Label();
            this.datefield1 = new Terminal.Gui.DateField();
            this.label1 = new Terminal.Gui.Label();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = false;
            this.Text = "";
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.label1.Width = 4;
            this.label1.Height = 1;
            this.label1.X = 0;
            this.label1.Y = 0;
            this.label1.Data = "label1";
            this.label1.Text = "DATE OF REPORT: ..........:";
            this.label1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label1);
            this.datefield1.Width = 12;
            this.datefield1.Height = 1;
            this.datefield1.X = 35;
            this.datefield1.Y = 0;
            this.datefield1.Secret = false;
            this.datefield1.Data = "datefield1";
            this.datefield1.Text = " 01/01/0001";
            this.datefield1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.datefield1);
            this.label2.Width = 4;
            this.label2.Height = 1;
            this.label2.X = 0;
            this.label2.Y = 1;
            this.label2.Data = "label2";
            this.label2.Text = "BEGINNING CASH ON HAND: ......:";
            this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label2);
            this.textfield1.Width = 4;
            this.textfield1.Height = 1;
            this.textfield1.X = 35;
            this.textfield1.Y = 1;
            this.textfield1.Secret = false;
            this.textfield1.Data = "textfield1";
            this.textfield1.Text = "";
            this.textfield1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.textfield1);
            this.label12.Width = 4;
            this.label12.Height = 1;
            this.label12.X = 55;
            this.label12.Y = 1;
            this.label12.Data = "label12";
            this.label12.Text = "TOTAL CASH ON HAND: .....:";
            this.label12.TextAlignment = Terminal.Gui.TextAlignment.Right;
            this.Add(this.label12);
            this.label14.Width = 4;
            this.label14.Height = 1;
            this.label14.X = 55;
            this.label14.Y = 2;
            this.label14.Data = "label14";
            this.label14.Text = "PURCHASE: .....:";
            this.label14.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label14);
            this.label13.Width = 4;
            this.label13.Height = 1;
            this.label13.X = 55;
            this.label13.Y = 3;
            this.label13.Data = "label13";
            this.label13.Text = "NEW MODE PURCHASE: ....";
            this.label13.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label13);
            this.label3.Width = 4;
            this.label3.Height = 1;
            this.label3.X = 0;
            this.label3.Y = 4;
            this.label3.Data = "label3";
            this.label3.Text = "Sales:........";
            this.label3.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label3);
            this.textfield2.Width = 4;
            this.textfield2.Height = 1;
            this.textfield2.X = 25;
            this.textfield2.Y = 4;
            this.textfield2.Secret = false;
            this.textfield2.Data = "textfield2";
            this.textfield2.Text = "<";
            this.textfield2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.textfield2);
            this.label15.Width = 4;
            this.label15.Height = 1;
            this.label15.X = 55;
            this.label15.Y = 4;
            this.label15.Data = "label15";
            this.label15.Text = "NEW PAWNS: ....";
            this.label15.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label15);
            this.label4.Width = 4;
            this.label4.Height = 1;
            this.label4.X = 0;
            this.label4.Y = 5;
            this.label4.Data = "label4";
            this.label4.Text = "Layaways";
            this.label4.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label4);
            this.textfield3.Width = 4;
            this.textfield3.Height = 1;
            this.textfield3.X = 25;
            this.textfield3.Y = 5;
            this.textfield3.Secret = false;
            this.textfield3.Data = "textfield3";
            this.textfield3.Text = "<";
            this.textfield3.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.textfield3);
            this.label16.Width = 4;
            this.label16.Height = 1;
            this.label16.X = 55;
            this.label16.Y = 5;
            this.label16.Data = "label16";
            this.label16.Text = "BANK DEPOSITS: ....";
            this.label16.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label16);
            this.label5.Width = 4;
            this.label5.Height = 1;
            this.label5.X = 0;
            this.label5.Y = 6;
            this.label5.Data = "label5";
            this.label5.Text = "TOTAL REGISTER SALES:........";
            this.label5.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label5);
            this.label17.Width = 4;
            this.label17.Height = 1;
            this.label17.X = 55;
            this.label17.Y = 6;
            this.label17.Data = "label17";
            this.label17.Text = "CASH PD OUT SUPPLIES: ....";
            this.label17.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label17);
            this.label6.Width = 4;
            this.label6.Height = 1;
            this.label6.X = 0;
            this.label6.Y = 7;
            this.label6.Data = "label6";
            this.label6.Text = "PAWN FEES: .....";
            this.label6.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label6);
            this.label18.Width = 4;
            this.label18.Height = 1;
            this.label18.X = 55;
            this.label18.Y = 7;
            this.label18.Data = "label18";
            this.label18.Text = "FREIGHT & POSTAGE: ....";
            this.label18.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label18);
            this.label7.Width = 4;
            this.label7.Height = 1;
            this.label7.X = 0;
            this.label7.Y = 8;
            this.label7.Data = "label7";
            this.label7.Text = "PAWN REDEEM: ....";
            this.label7.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label7);
            this.label19.Width = 4;
            this.label19.Height = 1;
            this.label19.X = 55;
            this.label19.Y = 8;
            this.label19.Data = "label19";
            this.label19.Text = "YARD & PEST CONTROL: ....";
            this.label19.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label19);
            this.label8.Width = 4;
            this.label8.Height = 1;
            this.label8.X = 0;
            this.label8.Y = 9;
            this.label8.Data = "label8";
            this.label8.Text = "WHOLESALE/PURC GIFT CARD: ....";
            this.label8.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label8);
            this.label20.Width = 4;
            this.label20.Height = 1;
            this.label20.X = 55;
            this.label20.Y = 9;
            this.label20.Data = "label20";
            this.label20.Text = "GIFT CARD REDEEMED: ...";
            this.label20.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label20);
            this.label9.Width = 4;
            this.label9.Height = 1;
            this.label9.X = 0;
            this.label9.Y = 10;
            this.label9.Data = "label9";
            this.label9.Text = "REGISTER TAX: .....";
            this.label9.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label9);
            this.label21.Width = 4;
            this.label21.Height = 1;
            this.label21.X = 55;
            this.label21.Y = 10;
            this.label21.Data = "label21";
            this.label21.Text = "MISCALLEANOUS EXPENSE: .....";
            this.label21.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label21);
            this.label10.Width = 4;
            this.label10.Height = 1;
            this.label10.X = 0;
            this.label10.Y = 11;
            this.label10.Data = "label10";
            this.label10.Text = "LAYAWAY TAX: ......";
            this.label10.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label10);
            this.label22.Width = 4;
            this.label22.Height = 1;
            this.label22.X = 55;
            this.label22.Y = 11;
            this.label22.Data = "label22";
            this.label22.Text = "ENDING CASH ON HAND: ...";
            this.label22.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label22);
            this.label11.Width = 4;
            this.label11.Height = 1;
            this.label11.X = 0;
            this.label11.Y = 12;
            this.label11.Data = "label11";
            this.label11.Text = "TOTAL TAX COLLECTED: .....";
            this.label11.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label11);
            this.label23.Width = 4;
            this.label23.Height = 1;
            this.label23.X = 10;
            this.label23.Y = 13;
            this.label23.Data = "label23";
            this.label23.Text = "TOTAL: >>";
            this.label23.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label23);
            this.label232.Width = 4;
            this.label232.Height = 1;
            this.label232.X = 65;
            this.label232.Y = 13;
            this.label232.Data = "label232";
            this.label232.Text = "TOTAL: >>";
            this.label232.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label232);
            this.label112.Width = 4;
            this.label112.Height = 1;
            this.label112.X = 1;
            this.label112.Y = 18;
            this.label112.Data = "label112";
            this.label112.Text = "LAYAWAY INCLUDING";
            this.label112.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label112);
            this.label1123.Width = 4;
            this.label1123.Height = 1;
            this.label1123.X = 30;
            this.label1123.Y = 18;
            this.label1123.Data = "label1123";
            this.label1123.Text = "OVER OR SHORT";
            this.label1123.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label1123);
            this.label11232.Width = 4;
            this.label11232.Height = 1;
            this.label11232.X = 55;
            this.label11232.Y = 18;
            this.label11232.Data = "label11232";
            this.label11232.Text = "PAWN FEES";
            this.label11232.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label11232);
            this.label1122.Width = 4;
            this.label1122.Height = 1;
            this.label1122.X = 1;
            this.label1122.Y = 19;
            this.label1122.Data = "label1122";
            this.label1122.Text = "TAX";
            this.label1122.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label1122);
            this.label112322.Width = 4;
            this.label112322.Height = 1;
            this.label112322.X = 55;
            this.label112322.Y = 19;
            this.label112322.Data = "label112322";
            this.label112322.Text = "PD PAWN INTEREST:";
            this.label112322.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label112322);
        }
    }
}
