
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.18.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Default {
    using Terminal.Gui;
    
    
    
    
    public partial class MyDialog {

        public static String AddTwoStrings(string one, string two)
        {
            int iOne = 0;
            int iTwo = 0;
            Int32.TryParse(one, out iOne);
            Int32.TryParse(two, out iTwo);
            return (iOne + iTwo).ToString();
        }

        string test;
        string pawnfees;
        
        public MyDialog() {
            InitializeComponent();
             
            
            button1.Clicked += () => {test=(string) textfield2.Text;textfield32.Text=test; Console.WriteLine(test);pawnfees = (string)textfield323.Text;textfield32.Text = AddTwoStrings(test, pawnfees);};


                            // Pawn fees textfield
                
                // TEST adding sales + pawn fees
                
            }

        }
    }

