
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.18.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Default {
    using Terminal.Gui;
    
    
    public partial class MyDialog {
        
        public MyDialog() {
            InitializeComponent();
        }
    }
}
